"""Fixed supplemental records for the local Central Library catalogue."""

SUPPLEMENTAL_MEMBERS = [
    ("Avery Patel", "student", "student"),
    ("Sofia Martinez", "student", "student"),
    ("Noah Williams", "student", "student"),
    ("Mia Johnson", "student", "student"),
    ("Liam Anderson", "student", "student"),
    ("Isabella Thomas", "student", "student"),
    ("Ethan Jackson", "student", "student"),
    ("Amelia White", "student", "student"),
    ("Lucas Harris", "student", "student"),
    ("Harper Martin", "student", "student"),
    ("Mason Thompson", "student", "student"),
    ("Evelyn Garcia", "student", "student"),
    ("Logan Robinson", "student", "student"),
    ("Abigail Clark", "student", "student"),
    ("James Lewis", "student", "student"),
    ("Ella Walker", "student", "student"),
    ("Benjamin Hall", "student", "student"),
    ("Grace Young", "student", "student"),
    ("Elijah Allen", "student", "student"),
    ("Chloe King", "student", "student"),
    ("Henry Wright", "student", "student"),
    ("Lily Scott", "student", "student"),
    ("Alexander Green", "student", "student"),
    ("Aria Baker", "student", "student"),
    ("Daniel Adams", "student", "student"),
    ("Nora Nelson", "student", "student"),
    ("Samuel Hill", "student", "student"),
    ("Zoe Campbell", "student", "student"),
    ("Owen Mitchell", "student", "student"),
    ("Layla Carter", "student", "student"),
    ("Gabriel Phillips", "student", "student"),
    ("Ivy Evans", "student", "student"),
    ("Julian Turner", "student", "student"),
    ("Leah Parker", "student", "student"),
    ("Caleb Collins", "student", "student"),
    ("Stella Edwards", "student", "student"),
    ("Jordan Davis", "staff", "staff"),
    ("Rachel Morgan", "staff", "staff"),
    ("Andre Wilson", "staff", "staff"),
    ("Mei Lin", "staff", "staff"),
    ("Carlos Rivera", "staff", "staff"),
    ("Fatima Hassan", "staff", "staff"),
    ("Peter Novak", "staff", "staff"),
    ("Simone Brooks", "staff", "staff"),
]

# title, author, category, publication year. These are consistent, seeded catalogue records.
SUPPLEMENTAL_BOOKS = [
    ("Artificial Intelligence: A Modern Approach", "Stuart Russell and Peter Norvig", "Artificial Intelligence", 2021),
    ("Deep Learning", "Ian Goodfellow, Yoshua Bengio and Aaron Courville", "Machine Learning", 2016),
    ("Hands-On Machine Learning with Scikit-Learn, Keras, and TensorFlow", "Aurélien Géron", "Machine Learning", 2022),
    ("Pattern Recognition and Machine Learning", "Christopher M. Bishop", "Machine Learning", 2006),
    ("The Elements of Statistical Learning", "Trevor Hastie, Robert Tibshirani and Jerome Friedman", "Machine Learning", 2009),
    ("Machine Learning: A Probabilistic Perspective", "Kevin P. Murphy", "Machine Learning", 2012),
    ("An Introduction to Statistical Learning", "Gareth James, Daniela Witten, Trevor Hastie and Robert Tibshirani", "Machine Learning", 2021),
    ("Reinforcement Learning: An Introduction", "Richard S. Sutton and Andrew G. Barto", "Machine Learning", 2018),
    ("Understanding Machine Learning", "Shai Shalev-Shwartz and Shai Ben-David", "Machine Learning", 2014),
    ("The Hundred-Page Machine Learning Book", "Andriy Burkov", "Machine Learning", 2019),
    ("Machine Learning Yearning", "Andrew Ng", "Machine Learning", 2018),
    ("Probabilistic Machine Learning: An Introduction", "Kevin P. Murphy", "Machine Learning", 2022),
    ("Probabilistic Machine Learning: Advanced Topics", "Kevin P. Murphy", "Machine Learning", 2023),
    ("Bayesian Reasoning and Machine Learning", "David Barber", "Machine Learning", 2012),
    ("Learning from Data", "Yaser S. Abu-Mostafa, Malik Magdon-Ismail and Hsuan-Tien Lin", "Machine Learning", 2012),
    ("Data Science from Scratch", "Joel Grus", "Data Science", 2019),
    ("Python for Data Analysis", "Wes McKinney", "Data Science", 2022),
    ("R for Data Science", "Hadley Wickham, Mine Çetinkaya-Rundel and Garrett Grolemund", "Data Science", 2023),
    ("Practical Statistics for Data Scientists", "Peter Bruce, Andrew Bruce and Peter Gedeck", "Data Science", 2020),
    ("Doing Data Science", "Cathy O'Neil and Rachel Schutt", "Data Science", 2013),
    ("Data Science for Business", "Foster Provost and Tom Fawcett", "Data Science", 2013),
    ("Fundamentals of Data Engineering", "Joe Reis and Matt Housley", "Data Engineering", 2022),
    ("Designing Data-Intensive Applications", "Martin Kleppmann", "Data Engineering", 2017),
    ("The Data Warehouse Toolkit", "Ralph Kimball and Margy Ross", "Data Engineering", 2013),
    ("Streaming Systems", "Tyler Akidau, Slava Chernyak and Reuven Lax", "Data Engineering", 2018),
    ("Database Internals", "Alex Petrov", "Data Engineering", 2019),
    ("Fundamentals of Database Systems", "Ramez Elmasri and Shamkant B. Navathe", "Database Systems", 2015),
    ("Database System Concepts", "Abraham Silberschatz, Henry F. Korth and S. Sudarshan", "Database Systems", 2019),
    ("SQL for Data Scientists", "Renee M. P. Teate", "Data Science", 2021),
    ("Storytelling with Data", "Cole Nussbaumer Knaflic", "Data Visualization", 2015),
    ("The Visual Display of Quantitative Information", "Edward R. Tufte", "Data Visualization", 2001),
    ("Fundamentals of Data Visualization", "Claus O. Wilke", "Data Visualization", 2019),
    ("Interactive Data Visualization for the Web", "Scott Murray", "Data Visualization", 2017),
    ("The Big Book of Dashboards", "Steve Wexler, Jeffrey Shaffer and Andy Cotgreave", "Data Visualization", 2017),
    ("Mining of Massive Datasets", "Jure Leskovec, Anand Rajaraman and Jeffrey D. Ullman", "Data Mining", 2020),
    ("Data Mining: Concepts and Techniques", "Jiawei Han, Micheline Kamber and Jian Pei", "Data Mining", 2011),
    ("Introduction to Information Retrieval", "Christopher D. Manning, Prabhakar Raghavan and Hinrich Schütze", "Information Retrieval", 2008),
    ("Speech and Language Processing", "Daniel Jurafsky and James H. Martin", "Natural Language Processing", 2025),
    ("Natural Language Processing with Python", "Steven Bird, Ewan Klein and Edward Loper", "Natural Language Processing", 2009),
    ("Transformers for Natural Language Processing", "Denis Rothman", "Natural Language Processing", 2022),
    ("Natural Language Processing with Transformers", "Lewis Tunstall, Leandro von Werra and Thomas Wolf", "Natural Language Processing", 2022),
    ("Computer Vision: Algorithms and Applications", "Richard Szeliski", "Computer Vision", 2022),
    ("Multiple View Geometry in Computer Vision", "Richard Hartley and Andrew Zisserman", "Computer Vision", 2004),
    ("Programming Computer Vision with Python", "Jan Erik Solem", "Computer Vision", 2012),
    ("Generative Deep Learning", "David Foster", "Machine Learning", 2023),
    ("Build a Large Language Model (From Scratch)", "Sebastian Raschka", "Artificial Intelligence", 2024),
    ("AI Engineering", "Chip Huyen", "Artificial Intelligence", 2025),
    ("Designing Machine Learning Systems", "Chip Huyen", "Machine Learning", 2022),
    ("Machine Learning Design Patterns", "Valliappa Lakshmanan, Sara Robinson and Michael Munn", "Machine Learning", 2020),
    ("Feature Engineering for Machine Learning", "Alice Zheng and Amanda Casari", "Machine Learning", 2018),
    ("Interpretable Machine Learning", "Christoph Molnar", "Machine Learning", 2022),
    ("Fairness and Machine Learning", "Solon Barocas, Moritz Hardt and Arvind Narayanan", "Artificial Intelligence", 2023),
    ("Weapons of Math Destruction", "Cathy O'Neil", "Data Science", 2016),
    ("Artificial Intelligence: A Guide for Thinking Humans", "Melanie Mitchell", "Artificial Intelligence", 2019),
    ("The Alignment Problem", "Brian Christian", "Artificial Intelligence", 2020),
    ("Human Compatible", "Stuart Russell", "Artificial Intelligence", 2019),
    ("Life 3.0", "Max Tegmark", "Artificial Intelligence", 2017),
    ("Algorithms to Live By", "Brian Christian and Tom Griffiths", "Computer Science", 2016),
    ("The Master Algorithm", "Pedro Domingos", "Machine Learning", 2015),
    ("The Book of Why", "Judea Pearl and Dana Mackenzie", "Statistics", 2018),
    ("Causal Inference: The Mixtape", "Scott Cunningham", "Statistics", 2021),
    ("Causal Inference in Statistics", "Judea Pearl, Madelyn Glymour and Nicholas P. Jewell", "Statistics", 2016),
    ("Introduction to Probability", "Joseph K. Blitzstein and Jessica Hwang", "Mathematics", 2019),
    ("All of Statistics", "Larry Wasserman", "Statistics", 2004),
    ("Bayesian Data Analysis", "Andrew Gelman et al.", "Statistics", 2013),
    ("The Signal and the Noise", "Nate Silver", "Statistics", 2012),
    ("Naked Statistics", "Charles Wheelan", "Statistics", 2013),
    ("Think Stats", "Allen B. Downey", "Statistics", 2014),
    ("Introduction to Linear Algebra", "Gilbert Strang", "Mathematics", 2016),
    ("Linear Algebra and Learning from Data", "Gilbert Strang", "Mathematics", 2019),
    ("Convex Optimization", "Stephen Boyd and Lieven Vandenberghe", "Mathematics", 2004),
    ("Numerical Optimization", "Jorge Nocedal and Stephen J. Wright", "Mathematics", 2006),
    ("Discrete Mathematics and Its Applications", "Kenneth H. Rosen", "Mathematics", 2018),
    ("The Algorithm Design Manual", "Steven S. Skiena", "Computer Science", 2020),
    ("Algorithms", "Robert Sedgewick and Kevin Wayne", "Computer Science", 2011),
    ("The Art of Computer Programming, Volume 1", "Donald E. Knuth", "Computer Science", 1997),
    ("Computer Networking: A Top-Down Approach", "James Kurose and Keith Ross", "Computer Science", 2021),
    ("Operating System Concepts", "Abraham Silberschatz, Peter B. Galvin and Greg Gagne", "Computer Science", 2018),
    ("Computer Systems: A Programmer's Perspective", "Randal E. Bryant and David R. O'Hallaron", "Computer Science", 2015),
    ("Structure and Interpretation of Computer Programs", "Harold Abelson and Gerald Jay Sussman", "Computer Science", 1996),
    ("The Pragmatic Programmer", "David Thomas and Andrew Hunt", "Software Engineering", 2019),
    ("Code: The Hidden Language of Computer Hardware and Software", "Charles Petzold", "Computer Science", 2022),
    ("Clean Architecture", "Robert C. Martin", "Software Engineering", 2017),
    ("The Mythical Man-Month", "Frederick P. Brooks Jr.", "Software Engineering", 1995),
    ("Domain-Driven Design", "Eric Evans", "Software Engineering", 2003),
    ("Accelerate", "Nicole Forsgren, Jez Humble and Gene Kim", "Software Engineering", 2018),
    ("The Phoenix Project", "Gene Kim, Kevin Behr and George Spafford", "Business", 2018),
    ("Thinking, Fast and Slow", "Daniel Kahneman", "Psychology", 2011),
    ("Range", "David Epstein", "Business", 2019),
    ("Factfulness", "Hans Rosling, Ola Rosling and Anna Rosling Rönnlund", "Social Sciences", 2018),
    ("The Design of Everyday Things", "Don Norman", "Design", 2013),
    ("Don't Make Me Think", "Steve Krug", "Design", 2014),
    ("The Innovator's Dilemma", "Clayton M. Christensen", "Business", 1997),
    ("Good Strategy Bad Strategy", "Richard Rumelt", "Business", 2011),
    ("The Fifth Risk", "Michael Lewis", "Public Policy", 2018),
    ("The Code Book", "Simon Singh", "History", 1999),
    ("A Brief History of Time", "Stephen Hawking", "Science", 1998),
    ("Cosmos", "Carl Sagan", "Science", 1980),
    ("The Martian", "Andy Weir", "Fiction", 2014),
    ("Project Hail Mary", "Andy Weir", "Fiction", 2021),
]
